from pathlib import Path
p=Path('index.html')
s=p.read_text()
if 'BATTLE <b>v3.12</b>' in s:
    print('v3.12 already applied')
    raise SystemExit(0)
if 'BATTLE <b>v3.11</b>' not in s:
    raise SystemExit('expected v3.11 base not found')
s=s.replace('BATTLE <b>v3.11</b>','BATTLE <b>v3.12</b>',1)
style="\n.patch-notes{margin:0 0 20px;padding:0;border:1px solid #30435c;border-radius:12px;background:#101a29;overflow:hidden}.patch-notes summary{cursor:pointer;padding:13px 15px;color:#d7f6a8;font-weight:800}.patch-notes .patch-body{padding:0 15px 14px;border-top:1px solid #26384f}.patch-version{padding:12px 0 4px}.patch-version+.patch-version{border-top:1px solid #26384f;margin-top:8px}.patch-version h3{margin:0 0 8px;font-size:15px}.patch-version ul{margin:0;padding-left:20px;color:#b9c9dd;font-size:13px;line-height:1.7}\n"
s=s.replace('</style><link rel="icon"',style+'</style><link rel="icon"',1)
needle='<section id="selection"><div class="mode-tabs" role="group" aria-label="게임 모드"><button id="mode-duel" type="button" aria-pressed="true">1대1 결투</button><button id="mode-boss" type="button" aria-pressed="false">👑 보스전 · 1대5</button><button id="mode-relay" type="button" aria-pressed="false">릴레이 · 3대3</button></div>'
notes='<details class="patch-notes"><summary>📒 패치노트 · v3.12</summary><div class="patch-body"><div class="patch-version"><h3>v3.12 · 달의 강림</h3><ul><li>패치노트 기능 추가: 주요 업데이트 내용을 게임 안에서 확인 가능.</li><li>흡혈귀 리메이크: 체력 30% 이하에서 🦇 박쥐로 변신하고 이동속도 100% 증가. 체력이 30%를 넘으면 다시 🧛 흡혈귀로 복귀.</li><li>신규 캐릭터 🌝 달 추가: 2초마다 반달 조각을 던져 피해 80. 조각이 돌아올 때 보름달 상태로 복귀.</li><li>달 궁극기: 전투 30초 후 하늘로 올라가 5초간 맵 전체에 붉은 피격 예고를 표시한 뒤 전장 전체 즉사 공격. 무적을 무시하며 팀 구분 없이 적용.</li></ul></div><div class="patch-version"><h3>v3.11 · 빌런 밸런스</h3><ul><li>빌런 일반 폭탄 피해 50, 다이너마이트 피해 70으로 조정.</li><li>불사조·거미·히어로 관련 이전 변경사항 유지.</li></ul></div></div></details>'
s=s.replace(needle,needle+notes,1)
s=s.replace("{id:'vampire',name:'흡혈귀',icon:'🧛',tag:'추격 · 흡혈',hp:1000,damage:75,speed:165,cooldown:.7,description:'상대를 쫓아가 물어뜯고, 실제로 준 피해의 35%만큼 자신의 체력을 회복해.',detail:'접촉 75 · 피해량의 35% 회복 · 최대 체력 초과 불가'},","{id:'vampire',name:'흡혈귀',icon:'🧛',tag:'흡혈 · 박쥐 변신',hp:1000,damage:75,speed:165,cooldown:.7,description:'상대를 물어뜯어 실제 피해의 35%를 회복해. 체력이 30% 이하가 되면 🦇 박쥐로 변신해 이동속도가 100% 증가하고, 30%를 넘게 회복하면 다시 흡혈귀로 돌아와.',detail:'접촉 75 · 피해량의 35% 회복 · HP 30% 이하: 박쥐 / 이동속도 ×2 · HP 30% 초과: 흡혈귀 복귀'},",1)
vill="{id:'villain',name:'빌런',icon:'🦹‍♂️',tag:'폭탄 · 행운 · 즉사',hp:1000,damage:50,speed:155,cooldown:3,description:'3초마다 특수 폭탄! 💣 50%: 피해 50, 🧨 30%: 피해 70, ❤️ 15%: 최대 체력 30% 회복, ☠️ 5%: 명중한 적 즉사.',detail:'직선 투척 · 하트는 자신 회복 · 확률은 보스도 동일 · 무적과 새의 부활은 유지'}\n];"
moon="{id:'villain',name:'빌런',icon:'🦹‍♂️',tag:'폭탄 · 행운 · 즉사',hp:1000,damage:50,speed:155,cooldown:3,description:'3초마다 특수 폭탄! 💣 50%: 피해 50, 🧨 30%: 피해 70, ❤️ 15%: 최대 체력 30% 회복, ☠️ 5%: 명중한 적 즉사.',detail:'직선 투척 · 하트는 자신 회복 · 확률은 보스도 동일 · 무적과 새의 부활은 유지'}\n,{id:'moon',name:'달',icon:'🌝',tag:'반달 조각 · 월하강림',hp:1000,damage:80,speed:150,cooldown:2,description:'2초마다 🌜 반달 조각을 던져 피해 80. 조각이 날아간 동안 자신은 🌛 반달이 되고, 조각이 돌아오면 다시 🌝 보름달이 돼. 전투가 30초를 넘기면 궁극기를 준비해.',detail:'반달 조각 80 · 쿨타임 2초 · 30초 후 궁극기 · 5초 예고 뒤 전장 전체 즉사 · 무적 무시 · 팀 구분 없음'}\n];"
s=s.replace(vill,moon,1)
s=s.replace("awakened:false,revivals:0,heroReady:false,transformAt:20/scale,heroPhase:'rush',retreatUntil:0,egg:false","awakened:false,revivals:0,heroReady:false,transformAt:20/scale,heroPhase:'rush',retreatUntil:0,vampireBat:false,moonHalf:false,moonShot:null,moonUltStarted:false,moonUltAt:30/scale,moonUltLandAt:0,moonUltPhase:'',egg:false",1)
s=s.replace("enemies(f){return this.fighters.filter(e=>e.team!==f.team&&e.health>0)}","enemies(f){return this.fighters.filter(e=>e.team!==f.team&&e.health>0&&e.moonUltPhase!=='air')}",1)
hero="transformHero(f){if(f.id!=='hero'||f.heroReady||f.health<=0||this.time<f.transformAt-1e-9)return;f.heroReady=true;f.icon='🦸';f.name='히어로';f.speed*=1.5;f.poison=null;f.burn=null;f.venom=null;f.stunUntil=0;f.slow=0;f.slowPower=0;f.rootSlow=0;f.rootSlowPower=0;if(f.capturedBy!==null){const captor=this.fighters[f.capturedBy];if(captor)this.releaseCapture(captor);f.capturedBy=null}this.effect(f,'변신 · 상태이상 해제!','skill')}\n"
extra="updateVampire(f){if(f.id!=='vampire'||f.health<=0)return;const low=f.health<=f.hp*.3;if(low&&!f.vampireBat){f.vampireBat=true;f.icon='🦇';f.name='박쥐';f.speed*=2;this.effect(f,'박쥐 변신!','skill')}else if(!low&&f.vampireBat){f.vampireBat=false;f.icon='🧛';f.name='흡혈귀';f.speed/=2;this.effect(f,'흡혈귀 복귀','skill')}}\nmoonSkill(f){if(f.id!=='moon'||f.health<=0)return;if(!f.moonUltStarted&&this.time>=f.moonUltAt-1e-9){f.moonUltStarted=true;f.moonUltPhase='air';f.moonUltLandAt=this.time+5;f.vx=0;f.vy=0;this.shots=this.shots.filter(s=>s.owner!==f.side);f.moonShot=null;f.moonHalf=false;f.icon='🌝';this.effect(f,'궁극기 준비!','doom');this.emit('🌝 달이 하늘로 올라갔어! 5초 뒤 전장 전체 타격')}if(f.moonUltPhase==='air'&&this.time>=f.moonUltLandAt-1e-9){f.moonUltPhase='landed';this.resolvingBlast=true;for(const e of this.fighters){if(e===f||e.health<=0)continue;e.health=0;e.trail=[];this.effect(e,'즉사','doom');if(this.formEgg(e))continue;}this.resolvingBlast=false;this.checkEnd();this.effects.push({x:360,y:360,text:'월하강림!',kind:'moonblast',side:f.side,team:f.team,life:1});this.emit('🌝 월하강림! 전장 전체 즉사')}}\nmoonThrow(f,e){if(f.id!=='moon'||f.cd>1e-9||f.moonHalf||f.moonUltPhase==='air')return;const a=this.aim(f,e),shot={x:f.x+a.x*(f.radius+8),y:f.y+a.y*(f.radius+8),vx:a.x,vy:a.y,owner:f.side,team:f.team,target:e.side,kind:'moon',icon:'🌜',damage:80*f.scale,radius:11*f.scale,speed:330*f.scale,life:6,returning:false,hit:false};this.shots.push(shot);f.moonShot=shot;f.moonHalf=true;f.icon='🌛';f.cd=f.cooldown;f.attack=.18/f.scale;this.effect(f,'반달 조각!','skill')}\n"
s=s.replace(hero,hero+extra,1)
s=s.replace(" this.transformHero(f);\n if(f.egg||f.stunUntil>this.time){f.attack=0;return}"," this.transformHero(f);this.updateVampire(f);this.moonSkill(f);\n if(f.moonUltPhase==='air'){f.attack=0;return}\n if(f.egg||f.stunUntil>this.time){f.attack=0;return}",1)
s=s.replace(" if(f.id==='villain'&&f.cd<=1e-9)this.throwBomb(f,e);\n if(['archer','mage','ninja','nerd'].includes(f.id)&&f.cd<=1e-9)this.fire(f,e);"," if(f.id==='villain'&&f.cd<=1e-9)this.throwBomb(f,e);\n if(f.id==='moon'&&f.cd<=1e-9)this.moonThrow(f,e);\n if(['archer','mage','ninja','nerd'].includes(f.id)&&f.cd<=1e-9)this.fire(f,e);",1)
s=s.replace("!['archer','mage','tree','ninja','nerd','spider','phoenix','hero','villain'].includes(f.id)","!['archer','mage','tree','ninja','nerd','spider','phoenix','hero','villain','moon'].includes(f.id)",1)
s=s.replace(" for(const f of this.fighters){this.transformHero(f);this.study(f)}"," for(const f of this.fighters){this.transformHero(f);this.updateVampire(f);this.moonSkill(f);this.study(f)}",1)
s=s.replace(" const alive=this.fighters.filter(f=>f.health>0);"," const alive=this.fighters.filter(f=>f.health>0&&f.moonUltPhase!=='air');",1)
move="  s.x+=s.vx*s.speed*dt;s.y+=s.vy*s.speed*dt;\n  if(s.x<22||s.x>698||s.y<22||s.y>698){"
moonmove="  if(s.kind==='moon'){if(s.returning){const a=this.aim(s,f);s.vx=a.x;s.vy=a.y;s.x+=s.vx*s.speed*dt;s.y+=s.vy*s.speed*dt;if(distance(s,f)<=f.radius+s.radius+7){s.life=0;f.moonShot=null;f.moonHalf=false;f.icon='🌝';this.effect(f,'보름달 복귀','skill');continue}}else{s.x+=s.vx*s.speed*dt;s.y+=s.vy*s.speed*dt;const e=this.enemies(f).find(v=>distance(s,v)<v.radius+s.radius);if(e&&!s.hit){this.attackProjectile(f,e,s);s.hit=true;s.returning=true}if(s.x<22||s.x>698||s.y<22||s.y>698)s.returning=true}continue}\n  s.x+=s.vx*s.speed*dt;s.y+=s.vy*s.speed*dt;\n  if(s.x<22||s.x>698||s.y<22||s.y>698){"
s=s.replace(move,moonmove,1)
s=s.replace("function ability(f){return f.id==='villain'?'폭탄 '+f.cooldown+'초 · 해골 확률 5%': f.id==='hero'?","function ability(f){return f.id==='moon'?(f.moonUltPhase==='air'?'궁극기 낙하까지 '+Math.max(0,f.moonUltLandAt-engine.time).toFixed(1)+'초':f.moonUltStarted?'궁극기 사용 완료':f.moonHalf?'🌛 반달 · 조각 회수 중':'🌝 보름달 · 궁극기까지 '+Math.max(0,f.moonUltAt-engine.time).toFixed(1)+'초'):f.id==='vampire'?(f.vampireBat?'🦇 박쥐 · 이동속도 +100%':'🧛 흡혈귀 · HP 30% 이하 박쥐 변신'):f.id==='villain'?'폭탄 '+f.cooldown+'초 · 해골 확률 5%': f.id==='hero'?",1)
anchor="ctx.fillText(mode==='relay'?'RELAY · 3 VS 3':mode==='boss'?'BOSS RAID · 1 VS 5':'NEON ARENA · 1 VS 1',360,44);\nfor(const f of engine.fighters){if(f.id!=='spider'||f.health<=0)continue;"
tele="ctx.fillText(mode==='relay'?'RELAY · 3 VS 3':mode==='boss'?'BOSS RAID · 1 VS 5':'NEON ARENA · 1 VS 1',360,44);\nfor(const m of engine.fighters){if(m.id==='moon'&&m.health>0&&m.moonUltPhase==='air'){ctx.save();const remain=Math.max(0,m.moonUltLandAt-engine.time);ctx.globalAlpha=.18+.08*Math.sin(engine.time*8);circle(360,360,470,'#8b0000');ctx.globalAlpha=1;ctx.strokeStyle='#ff1f1f';ctx.lineWidth=8;ctx.beginPath();ctx.arc(360,360,335,0,Math.PI*2);ctx.stroke();ctx.font='900 28px system-ui';ctx.fillStyle='#ff3030';ctx.fillText('월하강림 '+remain.toFixed(1)+'초',360,360);ctx.restore()}}\nfor(const f of engine.fighters){if(f.id!=='spider'||f.health<=0)continue;"
s=s.replace(anchor,tele,1)
s=s.replace("if(s.kind==='bomb'){ctx.rotate(-Math.atan2(s.vy,s.vx));ctx.font='28px \"Apple Color Emoji\",\"Segoe UI Emoji\",sans-serif';ctx.fillText(s.icon,0,0)}else if(s.kind==='flame')","if(s.kind==='bomb'){ctx.rotate(-Math.atan2(s.vy,s.vx));ctx.font='28px \"Apple Color Emoji\",\"Segoe UI Emoji\",sans-serif';ctx.fillText(s.icon,0,0)}else if(s.kind==='moon'){ctx.rotate(-Math.atan2(s.vy,s.vx));ctx.font='30px \"Apple Color Emoji\",\"Segoe UI Emoji\",sans-serif';ctx.fillText('🌜',0,0)}else if(s.kind==='flame')",1)
s=s.replace("for(const f of engine.fighters){const c=colors[f.team],r=f.radius;ctx.globalAlpha","for(const f of engine.fighters){if(f.moonUltPhase==='air')continue;const c=colors[f.team],r=f.radius;ctx.globalAlpha",1)
s=s.replace("ctx.fillStyle=(v.kind==='heal'||v.kind==='poison')?'#b8f279':(v.kind==='burn'||v.kind==='blast')?'#ffad63':v.kind==='forge'?'#ffd394':colors[v.team];","ctx.fillStyle=(v.kind==='doom'||v.kind==='moonblast')?'#8b0000':(v.kind==='heal'||v.kind==='poison')?'#b8f279':(v.kind==='burn'||v.kind==='blast')?'#ffad63':v.kind==='forge'?'#ffd394':colors[v.team];",1)
s=s.replace('기사 피해 감소는 60%, 흡혈귀 흡혈은 70%, 나무 감속은 80%로 강화돼.','기사 피해 감소는 60%, 흡혈귀 흡혈은 70%, 나무 감속은 80%로 강화돼. 보스 흡혈귀도 HP 30% 이하에서 박쥐로 변신하며 이동속도가 2배 더 빨라져.',1)
s=s.replace('보스 빌런은 1.5초마다 투척하며 폭탄 100·다이너마이트 140·하트 최대 체력 60% 회복, 종류별 확률은 동일해.','보스 빌런은 1.5초마다 투척하며 폭탄 100·다이너마이트 140·하트 최대 체력 60% 회복, 종류별 확률은 동일해. 보스 달은 반달 조각 160 / 1초, 15초 후 궁극기를 준비해 5초 뒤 전장 전체 즉사 공격을 사용해.',1)
p.write_text(s)
print('patched v3.12')
